### ISSUE TITLE
Arcanaeum Librarian typo in json file

### ISSUE THREAD

**Issue by acatai** [markjfisher/elder-scrolls-legends-sdk-java#1] opened 2019-07-07 13:23 UTC
There is `Arcaneum Librarian`  instead of `Arcanaeum Librarian`.

**Comment by markjfisher** [comment] 2019-07-08 09:53
I should probably map this twice with both spellings.
The actual card is spelled correctly (see https://www.legends-decks.com/card/746/arcanaeumlibrarian)

But the API that I refer to has it misspelled (https://api.elderscrollslegends.io/v1/cards?name=Arcaneum%20Librarian).

I raised this with the authors on their Discord channel along with some other issues, but now realise I should have kept the old spelling in their until they fix it in the API database too.
Thanks for raising this, I'll push a new map out in a new version later.

**Comment by markjfisher** [comment] 2019-07-11 13:33
Hi @acatai I've just looked into this further and my previous comment was incorrect so I've delete it.

The problem is that the API that I refer to has it misspelled (https://api.elderscrollslegends.io/v1/cards?name=Arcaneum%20Librarian), and not this SDK.

The JSON map file just allows me to create the mapping from 'official' Legends export code to the API internal code when decoding export strings. The name is just a convenience for reading, and not actually used anywhere in this SDK, only the code and id entries matter, which are correct.

I raised the misspelling with the authors on their Discord channel along with some other card issues. If they ever update their names in their database, it will be the fix the issue.

I'm going to close this issue, as it's an upstream issue with the source data.

**Closed as completed by markjfisher** 2019-07-11 13:33 UTC
